"""lora_init

Revision ID: d579925c719a
Revises:
Create Date: 2026-09-14 13:55:19.600164

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d579925c719a"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lora_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("at", sa.DateTime(), nullable=False),
        sa.Column("modem_id", sa.String(), nullable=True),
        sa.Column("dir", sa.String(length=2), nullable=False),
        sa.Column("t", sa.String(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "modems",
        sa.Column("modem_id", sa.String(), nullable=False),
        sa.Column("token_hash", sa.String(), nullable=False),
        sa.Column("agent_ver", sa.String(), nullable=True),
        sa.Column("modem_fw", sa.String(), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(), nullable=True),
        sa.Column("connected", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("modem_id"),
    )
    op.create_table(
        "outbox",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("modem_id", sa.String(), nullable=True),
        sa.Column("bld", sa.String(length=1), nullable=False),
        sa.Column("room", sa.Integer(), nullable=False),
        sa.Column("unit", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("new_ver", sa.Integer(), nullable=True),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("txn", sa.Integer(), nullable=True),
        sa.Column("ack_status", sa.Integer(), nullable=True),
        sa.Column("ack_detail", sa.Integer(), nullable=True),
        sa.Column("rssi", sa.Integer(), nullable=True),
        sa.Column("snr", sa.Float(), nullable=True),
        sa.Column("batt_mv", sa.Integer(), nullable=True),
        sa.Column("layout", sa.Integer(), nullable=True),
        sa.Column("fw", sa.Integer(), nullable=True),
        sa.Column("sched_ver", sa.Integer(), nullable=True),
        sa.Column("resv_ver", sa.Integer(), nullable=True),
        sa.Column("exam_ver", sa.Integer(), nullable=True),
        sa.Column("ident_ver", sa.Integer(), nullable=True),
        sa.Column("last_error", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("dispatched_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("outbox", schema=None) as batch_op:
        batch_op.create_index(
            "ix_outbox_pick", ["state", "modem_id", "priority", "id"], unique=False
        )

    op.create_table(
        "pending_devices",
        sa.Column("mac", sa.String(length=12), nullable=False),
        sa.Column("modem_id", sa.String(), nullable=True),
        sa.Column("fw", sa.Integer(), nullable=True),
        sa.Column("batt_mv", sa.Integer(), nullable=True),
        sa.Column("rssi", sa.Integer(), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("mac"),
    )
    op.create_table(
        "room_versions",
        sa.Column("bld", sa.String(length=1), nullable=False),
        sa.Column("room", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("ver", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("bld", "room", "kind"),
    )
    op.create_table(
        "terminal_status",
        sa.Column("bld", sa.String(length=1), nullable=False),
        sa.Column("room", sa.Integer(), nullable=False),
        sa.Column("unit", sa.Integer(), nullable=False),
        sa.Column("modem_id", sa.String(), nullable=True),
        sa.Column("mac", sa.String(), nullable=True),
        sa.Column("fw", sa.Integer(), nullable=True),
        sa.Column("batt_mv", sa.Integer(), nullable=True),
        sa.Column("rssi", sa.Integer(), nullable=True),
        sa.Column("snr", sa.Float(), nullable=True),
        sa.Column("sched_ver", sa.Integer(), nullable=True),
        sa.Column("resv_ver", sa.Integer(), nullable=True),
        sa.Column("exam_ver", sa.Integer(), nullable=True),
        sa.Column("ident_ver", sa.Integer(), nullable=True),
        sa.Column("layout", sa.Integer(), nullable=True),
        sa.Column("clock_stale", sa.Boolean(), nullable=False),
        sa.Column("low_batt", sa.Boolean(), nullable=False),
        sa.Column("uptime_h", sa.Integer(), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(), nullable=True),
        sa.Column("last_ack_at", sa.DateTime(), nullable=True),
        sa.Column("last_status_at", sa.DateTime(), nullable=True),
        sa.Column("sync_state", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("bld", "room", "unit"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("terminal_status")
    op.drop_table("room_versions")
    op.drop_table("pending_devices")
    with op.batch_alter_table("outbox", schema=None) as batch_op:
        batch_op.drop_index("ix_outbox_pick")

    op.drop_table("outbox")
    op.drop_table("modems")
    op.drop_table("lora_log")
    # ### end Alembic commands ###
