"""web_init

Revision ID: b3914933fd2a
Revises: d579925c719a
Create Date: 2026-09-14 14:43:03.725009

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b3914933fd2a"
down_revision: str | Sequence[str] | None = "d579925c719a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "schools",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("net_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("net_id"),
    )
    op.create_table(
        "buildings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("school_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("bld", sa.String(length=1), nullable=False),
        sa.Column("modem_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["modem_id"],
            ["modems.modem_id"],
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("school_id", "bld"),
    )
    op.create_table(
        "rooms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("building_id", sa.Integer(), nullable=False),
        sa.Column("room", sa.Integer(), nullable=False),
        sa.Column("units", sa.Integer(), nullable=False),
        sa.CheckConstraint("room BETWEEN 1 AND 9999"),
        sa.CheckConstraint("units IN (1, 2)"),
        sa.ForeignKeyConstraint(
            ["building_id"],
            ["buildings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("building_id", "room"),
    )
    op.create_table(
        "exam_periods",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("room_id", sa.Integer(), nullable=False),
        sa.Column("date_start", sa.Date(), nullable=False),
        sa.Column("date_end", sa.Date(), nullable=False),
        sa.CheckConstraint("id BETWEEN 1 AND 65535"),
        sa.ForeignKeyConstraint(["room_id"], ["rooms.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reservations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("room_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("s_h", sa.Integer(), nullable=False),
        sa.Column("s_m", sa.Integer(), nullable=False),
        sa.Column("e_h", sa.Integer(), nullable=False),
        sa.Column("e_m", sa.Integer(), nullable=False),
        sa.Column("type", sa.Integer(), nullable=False),
        sa.Column("subject", sa.String(), nullable=False),
        sa.Column("professor", sa.String(), nullable=False),
        sa.CheckConstraint("id BETWEEN 1 AND 65535"),
        sa.ForeignKeyConstraint(["room_id"], ["rooms.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "slots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("room_id", sa.Integer(), nullable=False),
        sa.Column("day", sa.Integer(), nullable=False),
        sa.Column("s_h", sa.Integer(), nullable=False),
        sa.Column("s_m", sa.Integer(), nullable=False),
        sa.Column("e_h", sa.Integer(), nullable=False),
        sa.Column("e_m", sa.Integer(), nullable=False),
        sa.Column("type", sa.Integer(), nullable=False),
        sa.Column("subject", sa.String(), nullable=False),
        sa.Column("professor", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["room_id"], ["rooms.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("room_id", "day", "s_h", "s_m"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("slots")
    op.drop_table("reservations")
    op.drop_table("exam_periods")
    op.drop_table("rooms")
    op.drop_table("buildings")
    op.drop_table("schools")
    # ### end Alembic commands ###
